# Generated by Django 5.2.7 on 2025-12-08 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_profile_rejection_reason_profile_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='choice_category',
            field=models.CharField(choices=[('Retail', 'Installer'), ('Whole Sale', 'Distributor'), ('End User', 'End User')], default=1, max_length=50),
            preserve_default=False,
        ),
    ]
