# Generated by Django 5.2.7 on 2025-12-09 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_profile_choice_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='choice_category',
        ),
        migrations.AddField(
            model_name='profile',
            name='chosen_category',
            field=models.CharField(blank=True, choices=[('Retail', 'Installer'), ('Whole Sale', 'Distributor'), ('End User', 'End User')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='category',
            field=models.CharField(choices=[('Retail', 'Installer'), ('Whole Sale', 'Distributor'), ('End User', 'End User')], default='End User', max_length=50),
        ),
    ]
