# Generated by Django 5.2.7 on 2025-12-09 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_remove_profile_choice_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationimage',
            name='image',
            field=models.ImageField(upload_to='verification_images'),
        ),
    ]
