# Generated by Django 5.2.7 on 2025-11-07 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_pickupstation_alter_order_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockalert',
            name='current_quantity',
        ),
        migrations.RemoveField(
            model_name='stockalert',
            name='expected_quantity',
        ),
        migrations.RemoveField(
            model_name='stockalert',
            name='item_code',
        ),
        migrations.RemoveField(
            model_name='stockalert',
            name='item_name',
        ),
        migrations.RemoveField(
            model_name='stockalert',
            name='notes',
        ),
    ]
