# Generated by Django 5.2.7 on 2025-11-07 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_stockalert_current_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockalert',
            name='expected_date',
            field=models.CharField(max_length=200),
        ),
    ]
