# Generated by Django 5.2.7 on 2025-11-10 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_stockalert_expected_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('success', 'Success'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
